Add IBM Copyright Statements
Terracotta-OSS/offheap-store pull request #83
Opened 2024-07-22 17:47 UTC by chrisdennis

2024-07-23 19:10 UTC, cljohnso commented
This project has IntelliJ IDEA copyright profiles committed -- they should be updated or removed.

2024-07-23 19:17 UTC, cljohnso commented
Several files contain a variant of `(all content copyright.* Terracotta, Inc.)` _in addition to_ the normal copyright/license.  Should these remain?

2024-07-23 19:18 UTC, cljohnso requested changes
At least one file needs a change; a few others _may_ need a change.

2024-07-23 19:18 UTC, cljohnso commented on README.adoc
> +  // Copyright Super iPaaS Integration LLC, an IBM Company 2024
Appear to have missed one below -- `(C) Terracotta, Inc., a Software AG company.` lacks the Super iPaaS variant.

2024-07-23 19:36 UTC, cljohnso requested changes
Several files contain a variant of `(all content copyright.* Terracotta, Inc.)` in addition to the normal copyright/license. Should these remain?

2024-07-24 14:11 UTC, chrisdennis commented
> Several files contain a variant of `(all content copyright.* Terracotta, Inc.)` _in addition to_ the normal copyright/license. Should these remain?

Remnant of the reintegration of OSS and EE offheap fragments. Will delete them.

2024-07-24 15:55 UTC, cljohnso approved these changes

2024-07-24 15:55 UTC, merged